// ============================================================
// HelpPanel.js — Contextual Help for PMs (Phase 8)
//
// Supply chain jargon is dense. This panel lets a PM understand
// exactly what every number and term means without leaving the dashboard.
// ============================================================

import React, { useState } from 'react';
import './HelpPanel.css';

const GLOSSARY = [
  {
    term: 'Risk Score (1–10)',
    definition:
      'A combined score from geopolitical zone data and live news signals. ' +
      '1–3 = stable, 4–6 = monitor, 7–10 = act now. ' +
      'News keywords like "strike" or "typhoon" push the score up in real time.',
  },
  {
    term: 'Critical Actions',
    definition:
      'Parts with a risk score above 6 (High). These are the components most ' +
      'likely to cause production delays if a disruption hits. Address these first.',
  },
  {
    term: 'Scenario Simulation',
    definition:
      'A "what-if" model that applies a disruption (e.g., port closure, geopolitical ' +
      'escalation) to your BOM and shows how risk scores and costs would change. ' +
      'Use this to prepare before a crisis, not after.',
  },
  {
    term: 'Vulnerability Scanner',
    definition:
      'An automated check for structural weaknesses: single-source high-risk parts, ' +
      'geographic concentration (too many parts from one region), high-value components ' +
      'exposed to price shocks, and manufacturer dependency.',
  },
  {
    term: 'Geopolitical Exposure',
    definition:
      'How much of your supply chain is concentrated in politically risky regions. ' +
      'A single region supplying 60% of your parts is a red flag even if today\'s scores look normal.',
  },
  {
    term: 'Lead Time Impact',
    definition:
      'An estimate of how many weeks your production could be delayed if the highest-risk ' +
      'parts were disrupted simultaneously. Driven by the number of High-risk parts.',
  },
  {
    term: 'Single-Source Risk',
    definition:
      'A part that has only one qualified supplier. If that supplier is also in a high-risk ' +
      'region, you have no fallback. The fix: qualify a secondary supplier in a stable region.',
  },
  {
    term: 'Concentration Risk',
    definition:
      'Multiple parts sourced from the same region or manufacturer. ' +
      'Resilient supply chains spread sourcing across multiple geopolitical zones.',
  },
  {
    term: 'AI vs Rule-Based',
    definition:
      'Recommendations marked "✦ AI" are generated by Claude (Anthropic\'s AI) and reference ' +
      'specific news events and part details. "⚙ Rules" means the API key isn\'t configured ' +
      'and the system uses a deterministic rule engine instead.',
  },
];

function HelpPanel() {
  const [isOpen, setIsOpen] = useState(false);
  const [search, setSearch] = useState('');

  const filtered = search.trim()
    ? GLOSSARY.filter(g =>
        g.term.toLowerCase().includes(search.toLowerCase()) ||
        g.definition.toLowerCase().includes(search.toLowerCase())
      )
    : GLOSSARY;

  return (
    <>
      {/* Floating help button */}
      <button
        className="help-trigger"
        onClick={() => setIsOpen(true)}
        title="Help & Glossary"
        aria-label="Open help panel"
      >
        ?
      </button>

      {/* Modal backdrop + panel */}
      {isOpen && (
        <div className="help-overlay" onClick={() => setIsOpen(false)}>
          <div className="help-panel" onClick={e => e.stopPropagation()}>

            <div className="help-header">
              <h2>Help &amp; Glossary</h2>
              <button className="help-close" onClick={() => setIsOpen(false)}>✕</button>
            </div>

            <p className="help-intro">
              CAMBER turns raw BOM data into actionable supply chain intelligence.
              Here's what every term means so you can brief leadership with confidence.
            </p>

            <input
              className="help-search"
              type="text"
              placeholder="Search terms..."
              value={search}
              onChange={e => setSearch(e.target.value)}
            />

            <div className="help-glossary">
              {filtered.map(({ term, definition }) => (
                <div key={term} className="help-entry">
                  <div className="help-term">{term}</div>
                  <div className="help-definition">{definition}</div>
                </div>
              ))}
              {filtered.length === 0 && (
                <p className="help-no-results">No matches for "{search}"</p>
              )}
            </div>

            <div className="help-footer">
              <strong>How to reduce risk:</strong> Qualify secondary suppliers for your top 3
              high-risk parts, spread sourcing across 2+ geopolitical zones, and run a scenario
              simulation before each planning cycle.
            </div>

          </div>
        </div>
      )}
    </>
  );
}

export default HelpPanel;
