// ============================================================
// RecommendationCard.js — Actionable Recommendation Display
//
// Phase 6 update:
//   - Shows recommendation_type badge (claude / rule-based)
//   - Shows parsed alternative suppliers list
//   - "Explain why" button calls POST /api/explain-risk for
//     a deeper AI explanation of the risk factors
// ============================================================

import React, { useState } from 'react';
import './RecommendationCard.css';

const API_BASE = process.env.REACT_APP_API_URL || 'http://localhost:5001';

function RecommendationCard({ part, riskLevel }) {
  const [explanation, setExplanation]   = useState(null);
  const [explaining, setExplaining]     = useState(false);

  const levelClass   = riskLevel.toLowerCase();
  const isAIPowered  = part.recommendation_source === 'claude';
  const recType      = part.recommendation_type || (isAIPowered ? 'claude' : 'rule-based');
  const alternatives = part.alternatives || [];

  async function handleExplain() {
    setExplaining(true);
    try {
      const res  = await fetch(`${API_BASE}/api/explain-risk`, {
        method:  'POST',
        headers: { 'Content-Type': 'application/json' },
        body:    JSON.stringify({ part }),
      });
      const data = await res.json();
      setExplanation(data.explanation || 'No explanation returned.');
    } catch (err) {
      setExplanation('Could not load explanation — check that the backend is running.');
    } finally {
      setExplaining(false);
    }
  }

  return (
    <div className={`recommendation-card ${levelClass}`}>

      {/* ---- HEADER ---- */}
      <div className="rec-header">
        <div>
          <h4>{part.part_name}</h4>
          <span className="rec-manufacturer">
            {part.manufacturer} · {part.country} · {part.risk_region}
          </span>
        </div>

        <div className="rec-header-right">
          {isAIPowered && (
            <span className="ai-badge" title="Generated by Claude AI">
              ✦ AI
            </span>
          )}
          <span className={`rec-score-badge score-${levelClass}`}>
            {part.risk_score}/10
          </span>
        </div>
      </div>

      {/* ---- RECOMMENDATION TYPE BADGE ---- */}
      <span className={`recommendation-type-badge ${recType}`}>
        {recType === 'claude' ? '✦ AI-Powered Analysis' : '⚙ Rule-Based'}
      </span>

      {/* ---- RECOMMENDATION TEXT ---- */}
      <p className="recommendation-text">{part.recommendation}</p>

      {/* ---- RECENT EVENTS ---- */}
      {part.recent_events && part.recent_events.length > 0 && (
        <div className="rec-events">
          <span className="rec-events-label">Recent events:</span>
          <ul className="recent-events">
            {part.recent_events.map((event, i) => (
              <li key={i}>{event}</li>
            ))}
          </ul>
        </div>
      )}

      {/* ---- RISK FACTOR TAGS ---- */}
      {part.risk_factors && part.risk_factors.length > 0 && (
        <div className="rec-factors">
          {part.risk_factors.map((factor, i) => (
            <span key={i} className="rec-factor-tag">{factor}</span>
          ))}
        </div>
      )}

      {/* ---- ALTERNATIVE SUPPLIERS ---- */}
      {alternatives.length > 0 && (
        <div className="alternatives-section">
          <div className="alternatives-label">Alternative Suppliers</div>
          <ul className="alternatives-list">
            {alternatives.map((alt, i) => (
              <li key={i}>{alt}</li>
            ))}
          </ul>
        </div>
      )}

      {/* ---- EXPLAIN WHY BUTTON ---- */}
      {isAIPowered && (
        <div>
          <button
            className="explain-btn"
            onClick={handleExplain}
            disabled={explaining}
          >
            {explaining ? 'Loading explanation…' : '⊕ Explain why this is risky'}
          </button>
          {explanation && (
            <div className="explain-text">{explanation}</div>
          )}
        </div>
      )}

    </div>
  );
}

export default RecommendationCard;
