// ============================================================
// RiskDashboard.js — Dashboard Root (Phase 7)
//
// This component owns:
//   1. The persistent header (badges, view toggles, export, reset)
//   2. View routing: overview ↔ detailed part view
//
// It does NOT own any data — everything flows down from App.js.
// ============================================================

import React, { useState } from 'react';
import './RiskDashboard.css';
import DashboardOverview  from './DashboardOverview';
import DetailedPartView   from './DetailedPartView';
import ExportButton       from './ExportButton';
import HelpPanel          from './HelpPanel';

function RiskDashboard({ data, onReset, newsMode, claudeReady, metrics, lastUpdated, vulnerabilities }) {
  const [viewMode,     setViewMode]     = useState('overview'); // 'overview' | 'detailed'
  const [selectedPart, setSelectedPart] = useState(null);

  function handleSelectPart(part) {
    setSelectedPart(part);
    setViewMode('detailed');
  }

  function handleBack() {
    setSelectedPart(null);
    setViewMode('overview');
  }

  const fmtTime = ts => ts
    ? new Date(ts).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    : null;

  return (
    <div className="dashboard">

      {/* ============================================================
          PERSISTENT HEADER
          Always visible regardless of view mode.
          PMs need one-click access to export, regardless of where
          they are in the dashboard.
          ============================================================ */}
      <div className="dashboard-header">
        <div>
          <h2>Risk Analysis Report</h2>
          <p className="dashboard-subtitle">
            {data.length} parts ·{' '}
            {metrics.highRiskCount > 0
              ? `${metrics.highRiskCount} critical`
              : 'no critical issues'}
            {lastUpdated && ` · Updated ${fmtTime(lastUpdated)}`}
          </p>
        </div>

        <div className="header-right">
          {/* Status badges */}
          {claudeReady === true && (
            <span className="news-badge live" title="Recommendations generated by Claude AI">
              ✦ AI
            </span>
          )}
          {claudeReady === false && (
            <span className="news-badge mock" title="Using rule-based recommendations">
              ⚙ Rules
            </span>
          )}
          {newsMode === 'live' && (
            <span className="news-badge live">✓ Live news</span>
          )}
          {newsMode === 'mock' && (
            <span className="news-badge mock">📋 Baseline</span>
          )}

          {/* View toggles (only relevant on overview) */}
          {viewMode === 'overview' && (
            <div className="view-toggles">
              <button className="view-toggle active">Overview</button>
            </div>
          )}

          <button className="reset-button" onClick={onReset}>
            ↩ New BOM
          </button>
        </div>
      </div>

      {/* ---- EXPORT ROW (overview only) ---- */}
      {viewMode === 'overview' && (
        <ExportButton bomData={data} metrics={metrics} />
      )}

      {/* ---- MAIN CONTENT ---- */}
      {viewMode === 'overview' && (
        <DashboardOverview
          metrics={metrics}
          bomData={data}
          onSelectPart={handleSelectPart}
          vulnerabilities={vulnerabilities}
        />
      )}

      {viewMode === 'detailed' && selectedPart && (
        <DetailedPartView
          part={selectedPart}
          onBack={handleBack}
        />
      )}

      {/* ---- FOOTER ---- */}
      <p className="disclaimer">
        ✓ Risk scores combine geopolitical zone data, live regional news signals, and{' '}
        {claudeReady ? 'AI-powered analysis via Claude.' : 'rule-based recommendations.'}
      </p>

      {/* Floating help button — always visible when dashboard is shown */}
      <HelpPanel />

    </div>
  );
}

export default RiskDashboard;
